name: Build Singularity

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup CLI
        uses: geode-sdk/cli/.github/actions/setup@v4.2.0
        with:
          version: v3.4.0

      - name: Setup Geode SDK
        shell: bash
        run: |
          geode sdk install "${{ github.workspace }}/geode-sdk-clone"

          # silly github actions wont refresh the env
          export GEODE_SDK="${{ github.workspace }}/geode-sdk-clone"
          echo "GEODE_SDK=$GEODE_SDK" >> $GITHUB_ENV

          # set a specific version that is guaranteed to work
          geode sdk update v4.2.0

      - name: Run CMake and build
        id: build
        shell: bash
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: build/Release/my-cocos-app.exe
